[package]

name = "sprs-ldl"
description = "Sparse cholesky factorization"
version = "0.5.0"
authors = ["Vincent Barrielle"]

readme = "README.rst"
license = "LGPL-2.1"
repository = "https://github.com/vbarrielle/sprs"
documentation = "https://vbarrielle.github.io/sprs/doc/sprs/"
keywords = ["sparse", "matrix", "cholesky", "factorization", "linalg"]

[dependencies]

num-traits = "0.1.32"


[dependencies.sprs]
version = "0.7.0"
path = ".."

